---
# tasks file for common

- name: Install TelnetClient
  win_feature:
    name: "{{feature}}"
    state: present

- name: Stop all services
  win_service:
    name: "{{services}}"  
    state: stopped
  notify: send_a_mail
  tags: stop_service