---
-
  hosts: all
  gather_facts: true # this will make not to gather facts before running tasks

  vars: 
    winyml = "{% if ansible_env.subrole == 'web' %}webrole.yml{% elif ansible_env.mainrole == 'win' -%}winrole.yml{% endif %}"   
  tasks: 
    - name: Create Folder &Stop Service
      debug:
           msg: play1-task1
  
    - include_tasks: "{{winyml}}"
  #  - include_tasks: winrole.yml   
...