---
-
  hosts: all
  gather_facts: true # this will make not to gather facts before running tasks

  tasks: 
    - name: Create Folder &Stop Service
      debug:
           msg: play1-task1
    - include_tasks: {% if ansible_env.subrole == "web" -%}winrole.yml{% elif ansible_env.mainrole == "win" -%}{% endif %}
  #  - include_tasks: winrole.yml   
...